apiVersion: apps/v1
kind: Deployment
metadata:
  name: encontros-tech
  labels:
    app: encontros-tech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encontros-tech
  template:
    metadata:
      labels:
        app: encontros-tech
    spec:
      containers:
      - name: encontros-tech
        image: saulohjr/encontros-tech:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: encontros-tech-db-secret
              key: DATABASE_URL
        - name: SERVICE_NAME
          value: "encontros-tech"
        - name: SERVICE_VERSION
          value: "1.0.0"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DEBUG
          value: "False"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: PROMETHEUS_MULTIPROC_DIR
          value: "/tmp/prometheus_multiproc"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
       
---
apiVersion: v1
kind: Service
metadata:
  name: encontros-tech-service
  labels:
    app: encontros-tech
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: encontros-tech
